### ISSUE TITLE
Error deploying to Heroku

### ISSUE THREAD

**Issue by nkirui** [schoolofcode-me/stores-rest-api#1]
After deploying it, the  program just doesn't run and Heroku log shows the following error : `2018-03-01T07:57:14.467307+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=store-restapi.herokuapp.com request_id=40951602-c722-4f5c-8b95-6276998cc544 fwd="197.232.50.88" dyno= connect= service= status=503 bytes= protocol=https
2018-03-01T07:57:16.339070+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=store-restapi.herokuapp.com request_id=db8e8604-5503-4221-aa17-8b68258cc3b7 fwd="197.232.50.88" dyno= connect= service= status=503 bytes= protocol=https`

After looking through some similar problems and errors on  deployment, I tried:
`heroku ps:scale web=1`
and got:
`Scaling dynos... !
 !  Couldn't find that formation.`

**Comment by CristianoYL** [comment]
Hi Nkirui,

It's very likely that there's something wrong in the deployment process. The error log you provided is not conclusive, and I'm assuming that there're more logs.

I've personally deployed this project several times and have no trouble with it. And most students have done the same. I'm sure it will work out. Please feel free to post a question in the course Q&A section, and you can get much more speedy help there.

Kind regards
